[package]
name = "json-hand"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#fltk = "^1.4"
fltk = { version = "^1.4", git = "https://github.com/fltk-rs/fltk-rs" }